services:
  backend:
    build: ./backend
    container_name: api-proju
    ports:
      - "3035:3035"
    depends_on:
      - postgres 

    volumes:
      - ./backend:/app
      # - ./backend/node_modules:/app/node_modules 
      - /app/node_modules 
    env_file:
      - ./backend/.env

  frontend:
    build: ./frontend
    container_name: front-proju
    ports:
      - "3060:3000"
    environment:
      - HOST=0.0.0.0
    volumes:
      - ./frontend:/app:delegated
      - /app/node_modules
      # - ./frontend/node_modules:/app/node_modules 
    # command: "npm start"

    depends_on:
      - backend

  postgres:
    image: postgres:17
    container_name: db-proju
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: proJu
    ports:
      - "5941:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data



volumes:
  pgdata: